### ISSUE TITLE
ulozit postgresql db na github

### ISSUE THREAD

**Issue by tukusejssirs** [tukusejssirs/Konpoz#1]
este neviem ako, ale bolo by to vhodne …

**Comment by zorvar** [comment]
to sa neda ulozit, ta musi bezat na servri a potrebuje aj apac a php mat
nainstalovane

2015-10-12 23:45 GMT+02:00 tukusejssirs <notifications@github.com>:

> este neviem ako, ale bolo by to vhodne …
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tukusejssirs/Konpoz/issues/1>.
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by zorvar** [comment]
to je prave to preco by som potreboval beziaci server a nie iba ulozisko,
keby sme tak vymysleli ako spravit server za NATom, kludne by som obetoval
niektory komp co mam u teba

Dňa 12. októbra 2015, 23:46, Zoran Varga <zorvar@gmail.com> napísal(-a):

> to sa neda ulozit, ta musi bezat na servri a potrebuje aj apac a php mat
> nainstalovane
>
> 2015-10-12 23:45 GMT+02:00 tukusejssirs <notifications@github.com>:
>
>> este neviem ako, ale bolo by to vhodne …
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tukusejssirs/Konpoz/issues/1>.
>>
>
>
>
> --
> Zoran Varga
> Rudohorská 30
> Banská Bystrica 97411
> tel. 0907 267 535
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by zorvar** [comment]
teda server nie je problem ale aby sme sa k nemu vsetci dostali, inak v
podstate to mam hotove skoro, teda v principe, este som ladil take veci aby
vymazavalo duplicitne riadky ked niekto zada to iste viackrat

Dňa 12. októbra 2015, 23:49, Zoran Varga <zorvar@gmail.com> napísal(-a):

> to je prave to preco by som potreboval beziaci server a nie iba ulozisko,
> keby sme tak vymysleli ako spravit server za NATom, kludne by som obetoval
> niektory komp co mam u teba
>
> Dňa 12. októbra 2015, 23:46, Zoran Varga <zorvar@gmail.com> napísal(-a):
>
> to sa neda ulozit, ta musi bezat na servri a potrebuje aj apac a php mat
>> nainstalovane
>>
>> 2015-10-12 23:45 GMT+02:00 tukusejssirs <notifications@github.com>:
>>
>>> este neviem ako, ale bolo by to vhodne …
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/tukusejssirs/Konpoz/issues/1>.
>>>
>>
>>
>>
>> --
>> Zoran Varga
>> Rudohorská 30
>> Banská Bystrica 97411
>> tel. 0907 267 535
>>
>
>
>
> --
> Zoran Varga
> Rudohorská 30
> Banská Bystrica 97411
> tel. 0907 267 535
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by tukusejssirs** [comment]
tak aspon zalohu db by sme mohli mat tu (teda vzdy aktualnu … mohol by si ju aktualizovat Ty) … da sa to pomocou tohto prikazu:
```bash
pg_dump menodatabazy -U menopouzivatela > konpoz.sql
```

pripadne kukni `man pg_dump` …

co sa tyka serveru, ani muh, ani beh od nikoho, iba my dvaja tu debatime … verim, ze kazdy ma svoje povinnosti, avsak i skola medzi ne patri …
