### ISSUE TITLE
The requested URL `/insert.php` was not found on this server.

### ISSUE THREAD

**Issue by tukusejssirs** [tukusejssirs/Konpoz#2]
@zorvar, prosim Ta, skus najst vo Svojom pocitaci subor `insert.php` a uploadni ho do priecinku `/webstranka` tu na github-e. Myslim, ze je tiez potrebny. Vdaka. :)

Akoze ten `insert.php`, ktory je volany nasledovnym tagom v subore [index.html](https://github.com/tukusejssirs/Konpoz/blob/master/webstranka/index.html) v [15.](https://github.com/tukusejssirs/Konpoz/blob/master/webstranka/index.html#L15) riadku:
```html
<form name="insert" action="insert.php" method="POST" >

**Comment by zorvar** [comment]
insert.php je vlastne index.html, takze uz je v podstate tam

2015-10-16 23:00 GMT+02:00 tukusejssirs <notifications@github.com>:

> Assigned #2 <https://github.com/tukusejssirs/Konpoz/issues/2> to @zorvar
> <https://github.com/zorvar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tukusejssirs/Konpoz/issues/2#event-437966973>.
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by tukusejssirs** [comment]
mozno, ano v `index.html` sa nenachadza ziadna php funkcia `index.php` … vo svojom pc nemas sudobr `index.html` nahodou nazvany `index.php`?

**Comment by zorvar** [comment]
pracujem na tom, chces ale dat index html zvlast a naimportovat nam index
php? alebo to dame na jeden subor index html?

2015-10-17 11:41 GMT+02:00 tukusejssirs <notifications@github.com>:

> mozno, ano v index.html sa nenachadza ziadna php funkcia index.php … vo
> svojom pc nemas sudobr index.html nahodou nazvany index.php?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tukusejssirs/Konpoz/issues/2#issuecomment-148899238>.
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by tukusejssirs** [comment]
v podstate mi jedno, aka bude implementacia, resp umiestnenie skriptu ... len som to uploadol na jednu stranku (akoze test, aby sme sa potom s tym uz menej hrali), no vypisuje mi tento error ... avsak zda sa, ze si to bud musim lepsie nastudovat (to php) abo to budes musiet spravit Ty ([stranka](konpoz.heliopost.org]; host: konpoz.helipost.org; ftp_user: konpoz; ftp_paswd: aiex2014umb) ...

**Comment by zorvar** [comment]
jjop som ti vravel ze ze apache postgresql a php musia bezat na servri ak
to ma fungovat

Dňa 17. októbra 2015, 11:53, tukusejssirs <notifications@github.com>
napísal(-a):

> v podstate mi jedno, aka bude implementacia, resp umiestnenie skriptu ...
> len som to uploadol na jednu stranku (akoze test, aby sme sa potom s tym uz
> menej hrali), no vypisuje mi tento error ... avsak zda sa, ze si to bud
> musim lepsie nastudovat (to php) abo to budes musiet spravit Ty (stranka ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tukusejssirs/Konpoz/issues/2#issuecomment-148901151>.
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535

**Comment by tukusejssirs** [comment]
(dako mi neodoslalo koniec predchadzajucej spravy, toto tam malo este byt: [stranka](konpoz.heliohost.org]; host: `konpoz.heliohost.org`; ftp_user: `konpoz`; ftp_password: `aiex2014umb`; nazov_db: `konpoz_prezentacie`, bo db sa tam musia zacinat `konpoz_`)

na [heliohost-e](heliohost.org) *je* postgresql a php … neviem vsak, ci je tam apache …

btw, zverejnujes tu osobne informacie tym, ze odpovedas na email a neotvorist si stranku [issue #2](https://github.com/tukusejssirs/Konpoz/issues/2), napr Tvoja posledna sprava na github-e vyzera takto:

**Comment by tukusejssirs** [comment]
uz som Ti odstranil vsetky *citlive* udaje zo sprav v tejto issue #2

**Comment by zorvar** [comment]
ja nechcem chatovat na isue dva, len si niekedy nevsimnem odkial pises,
uprednostnujem vylucne osobnu komunikaciu, ked mi chces nieco napisat pis
mi na mejl, tymto si nastavujem tukusejsyrs na spam

Dňa 17. októbra 2015, 12:04, tukusejssirs <notifications@github.com>
napísal(-a):

> (dako mi neodoslalo koniec predchadzajucej spravy, toto tam malo este byt:
> stranka
>
> na heliohost-e <http://heliohost.org> *je* postgresql a php … neviem
> vsak, ci je tam apache …
>
> btw, zverejnujes tu osobne informacie tym, ze odpovedas na email a
> neotvorist si stranku issue #2
> <https://github.com/tukusejssirs/Konpoz/issues/2>, napr Tvoja posledna
> sprava na github-e vyzera takto:
>
> jjop som ti vravel ze ze apache postgresql a php musia bezat na servri ak
> to ma fungovat
>
> Dňa 17. októbra 2015, 11:53, tukusejssirs notifications@github.com
> napísal(-a):
> …
>
> v podstate mi jedno, aka bude implementacia, resp umiestnenie skriptu ...
> len som to uploadol na jednu stranku (akoze test, aby sme sa potom s tym uz
> menej hrali), no vypisuje mi tento error ... avsak zda sa, ze si to bud
> musim lepsie nastudovat (to php) abo to budes musiet spravit Ty (stranka
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <#2 <https://github.com/tukusejssirs/Konpoz/issues/2> (comment)>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tukusejssirs/Konpoz/issues/2#issuecomment-148901529>.
>



-- 
Zoran Varga
Rudohorská 30
Banská Bystrica 97411
tel. 0907 267 535
