### ISSUE TITLE
komentar k designu stranky

### ISSUE THREAD

**Issue by siduska** [tukusejssirs/Konpoz#3]
otto, prepac, ale ten navrh stranky mi pride taky bez ladu a skladu, trochu som sa pohrala s designom stranky ako by som si to predstavovala, nevravim ze je to konecna verzia, ale take daco...farby, tvary loggo atd. mozme menit prisposobit, ficurky pridat atd., kludne pripomienkujte...lepsie sa mi bude robit html ked to bude ako-tak poriesene..., este ma napadlo ze tam mozme pridat vyhladavanie..., mozno aj ja to este upravim, zatial je to takto...syn je chory teraz takze dostanem sa k tomu teraz len ked sa da...
![grafika_navrh01](https://cloud.githubusercontent.com/assets/15051606/10757502/bd055f9c-7cab-11e5-982b-6a37c13cbd96.jpg)
![grafika_navrh02_akcie](https://cloud.githubusercontent.com/assets/15051606/10757504/c0ae1670-7cab-11e5-85fb-59a0fc86fdc0.jpg)
![grafika_navrh02_kalendar](https://cloud.githubusercontent.com/assets/15051606/10757506/c4e295f4-7cab-11e5-9908-ed49d2ecd767.jpg)

**Comment by zorvar** [comment]
jaj, trosku jemnejsie s tymi farbami, ak by sa dalo,

**Comment by siduska** [comment]
o.k. :-) ...farby su zatial take co mi prisli prve pod ruku...
